### ISSUE TITLE
Versions follow-up

### ISSUE THREAD

**Issue by robertSt7** [pimcore/studio-backend-bundle#104]
follow-up https://github.com/pimcore/studio-backend-bundle/pull/50

- [x] remove `elementModificationDate` from `Cleanup versions` endpoint
- [x] create endpoint to show image version
- [x] create endpoint to download other formats

**Comment by lukmzig** [comment]
@robertSt7. just fyi, we decided we will not provide base64 encoded image.
Instead we will rpovide 2 new endpoints:
1. returning Streamed content for image version preview based on the version ID
2. endpoint to download binary file directly for other types
