### ISSUE TITLE
Create document preview endpoint

### ISSUE THREAD

**Issue by markus-moser** [pimcore/studio-backend-bundle#114]
This issues is related to https://github.com/pimcore/studio-ui-bundle/issues/75.

We need a pendant to the admin UI classic bundle's `/asset/get-preview-document` call to be able to show a (PDF) preview for documents.

![image](https://github.com/pimcore/studio-backend-bundle/assets/4639428/dea886bb-1e39-49c6-a36e-d5414220c124)

**Comment by lukmzig** [comment]
New endpoint was added by this PR:
https://github.com/pimcore/studio-backend-bundle/pull/147

PDF stream can be retrieved by ID under this path
https://github.com/pimcore/studio-backend-bundle/pull/147/files#diff-fcb240ab2ddf2151e4bd2a9dc8bb588ffb3b67686d866d51b7afa71b3b5016fbR70

**Comment by mattamon** [comment]
Resolved by #147
