### ISSUE TITLE
Versions

### ISSUE THREAD

**Issue by robertSt7** [pimcore/studio-backend-bundle#131]
Can't get every version image
- save an asset
- change the image in the edit tab and save the image and the asset
- try to get every version image 
`net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK)`

**Comment by lukmzig** [comment]
@robertSt7 @markus-moser 

We found out that there is a bug in the core currently which is causing this issue. 
Methods `getFileSize() `and `getDimensions()` of the Asset class are currently always returning the values of the latest versions. You can also see in the classic UI that these values are incorrect for the older versions in the table and always return only the latest version values:
https://github.com/pimcore/pimcore/blob/11.x/models/Asset.php#L1547
As we are now using the  `Content-Length` for our Stream responses as it should be there, this caused the miss-match.
For the backend API the issues should be resolved by this PR:  https://github.com/pimcore/studio-backend-bundle/pull/135

Should we create a BUG issue in the core for this as well?

**Comment by markus-moser** [comment]
@lukmzig Great, thanks for solving it. Let's for the moment concentrate on building our new stuff in a improved way 👍 

One question to your solution in the backend bundle. Does this respect the flysystem abstraction for the `pimcore.version.storage` storage? So does it for example work also when the versions are stored in S3?

**Comment by mattamon** [comment]
@markus-moser I will create a ticket so will test it, currently we cannot really say if it works
