### ISSUE TITLE
Asset update

### ISSUE THREAD

**Issue by markus-moser** [pimcore/studio-backend-bundle#134]
Related to https://github.com/pimcore/studio-ui-bundle/issues/173#issuecomment-2152284720

The list of fields for the asset update looks like this:
- partentId
- key
- locked
- all asset metadata attributes for the various types
- focal point 
- properties
- data (for text files the text file content)
- scheduler? (we have there a separate endpoint but in addition to the specific scheduler save button the scheduler should also be saved when the global save button get's pressed. do we solve this with 2 calls?)

In addition to that we need to check that the `userModification` gets automatically updated with the authenticated user.

Later when we build the asset upload we need some more attributes, but I guess this will be then a separate endpoint.

Hopefully I found all attributes but at least there should not be many which are missing in my list.

All of them should be built as discussed in a PATCH update fashion (so that only sent fields are updated and not sent fields remain untouched).

**Comment by mattamon** [comment]
@markus-moser I added all needed properties in #150 

For the schedules I would send a separate request. Schedules are not part of the versions so imho it would not make sense, to send it via an update for the asset. 

Please let me know if there is something else you need or it is not working as expected.

**Comment by markus-moser** [comment]
@mattamon Thanks, we will check. Yes for the scheduler this is fine. We should do some kind of dirty check in the frontend to see if the second request is relevant.
