### ISSUE TITLE
[Task] Test versions file size and dimensions with s3

### ISSUE THREAD

**Issue by mattamon** [pimcore/studio-backend-bundle#136]
Based on the problem here, the solution needs to tested with S3 storage

https://github.com/pimcore/studio-backend-bundle/issues/131#issuecomment-2165807446

**Comment by mattamon** [comment]
@markus-moser  https://github.com/pimcore/studio-backend-bundle/pull/135 also works perfectly with AWS. Tested it with MinIO

**Comment by markus-moser** [comment]
Nice, thanks for testing it!
