### ISSUE TITLE
[Permission Management] Schedules

### ISSUE THREAD

**Issue by mattamon** [pimcore/studio-backend-bundle#143]
Currently schedules need the "settings" permission to be shown.

The schedules can also be deleted and saved. 

Problem is that schedules work properly, you also need the versions. 

The schedule repository checks now both versions: https://github.com/pimcore/studio-backend-bundle/blob/1.x/src/Schedule/Repository/ScheduleRepository.php#L179

Is there a reason why it only needs the settings, even thought the functionality is not given with only the settings permissions?

**Comment by lukmzig** [comment]
@fashxp could you please provide us with a feedback here? :)

**Comment by fashxp** [comment]
> Is there a reason why it only needs the settings, even thought the functionality is not given with only the settings permissions?

I guess not :-) 

So I think checking for `versions` and `settings` permission is fine :+1:

**Comment by mattamon** [comment]
@fashxp Thank you! 
Then I can close the ticket, since no changes are needed :)
