### ISSUE TITLE
Sorting of assets should be alphabetically 

### ISSUE THREAD

**Issue by vin0401** [pimcore/studio-backend-bundle#190]
The endpoints for Asset listings seem to deliver the data sorted based on the latest update.

In the classic UI it's sorted alphabetically. I guess, we should implement this again. At the moment, in the studio UI, assets jump to the last place/page after an update was performed.

**Comment by mattamon** [comment]
@markus-moser, there is a sorter in GDI right?

**Comment by markus-moser** [comment]
@mattamon Just add this search modifier:
https://github.com/pimcore/generic-data-index-bundle/blob/1.x/src/Model/Search/Modifier/Sort/Tree/OrderByFullPath.php

We will need more (generic) sort modifiers in the future but for the default and tree sort this should be fine.

**Comment by mattamon** [comment]
@markus-moser, @vin0401 
https://github.com/pimcore/studio-backend-bundle/pull/192
