### ISSUE TITLE
[Bug]: when installing on a fresh pimcore instance the installer will cause an error

### ISSUE THREAD

**Issue by alexz707** [pimcore/studio-backend-bundle#241]
### Studio API version

1

### Steps to reproduce

Try to install Studio Backend

### Actual Behavior

`TypeError {#2023
  #message: "Symfony\Component\Mercure\Jwt\LcobucciFactory::__construct(): Argument #1 ($secret) must be of type string, null given, called in /var/www/html/var/cache/dev/ContainerGhfP6eL/App_KernelDevDebugContainer.php on line 7980"
  #code: 0
  #file: "./vendor/symfony/mercure/src/Jwt/LcobucciFactory.php"
  #line: 46
  trace: {
`

### Expected Behavior

Should just install the backend

**Comment by mattamon** [comment]
@alexz707 will the doc update #240 change anything since it is about the LcobucciFactory? It should right?
