### ISSUE TITLE
[Task]: Verify we are using Flysystem everywhere

### ISSUE THREAD

**Issue by alexz707** [pimcore/studio-backend-bundle#244]
### Studio API version

1

### Steps to reproduce

Currently there are some implementations like unlink, fopen, ... which are not compatible with Flysystem (https://flysystem.thephpleague.com/docs/)

### Actual Behavior

We need to make sure to only use the Flysystem access methods so there is no problem if someone wants to use a different filesystem than the local one.

### Expected Behavior

to be fully compatible with Flysystem

**Comment by dpfaffenbauer** [comment]
*Flysystem with a lower case `s` ;)

**Comment by mattamon** [comment]
@dpfaffenbauer there you go :P changed it
