### ISSUE TITLE
[Task] Tags followup: Batch methods + Mercure events

### ISSUE THREAD

**Issue by alexz707** [pimcore/studio-backend-bundle#257]
Still open is the batch handling of the tag assignment (maybe use another approach -> assign to childs instead of sending all ids)

Mercure notification should be also done as soon as batch assignment is ready.

-> check permission handling especially with batch operations.

**Comment by lukmzig** [comment]
@markus-moser  please use the endpoint `/tags/batch/{operation}/{elementType}/{id}`
you can specifiy the operation:
- assign
- replace
