### ISSUE TITLE
[Bug] All generic execution engine errors try to send an update to mercure

### ISSUE THREAD

**Issue by fashxp** [pimcore/studio-backend-bundle#269]
### Studio API version

1.x-dev

### Steps to reproduce

e.g. create a copilot action that fails with an exception.

### Actual Behavior

Tries to send an update to mercure, see corresponding log entries in copilot logs... 

![image](https://github.com/user-attachments/assets/3e904967-458f-4a83-8954-ed545fe14ee9)

![image](https://github.com/user-attachments/assets/2470fe0c-bc9e-4a94-ab4c-357c55a82cc2)

### Expected Behavior

not sure, if all failed jobs should send an update to mercure

**Comment by fashxp** [comment]
this actually destroys error handling of GEE as a whole. 
it is also the reason for https://github.com/pimcore/copilot-bundle/issues/542

**Comment by lukmzig** [comment]
Should be resolved by https://github.com/pimcore/studio-backend-bundle/pull/278/files#diff-aca7e22c72dd97a41bb7e00e393ea25e880b5223980f0daa0487df9b5b0bdf72R55-R64
