### ISSUE TITLE
[Notes&Event] User should be saved when creating a new note

### ISSUE THREAD

**Issue by markus-moser** [pimcore/studio-backend-bundle#272]
When adding a note via the notes API the user of the note should be set to the authenticated user. Currently the userId and userName are null when a new note is added and then the note list is fetched again.

**Comment by lukmzig** [comment]
@markus-moser user should be set now
https://github.com/pimcore/studio-backend-bundle/pull/275

**Comment by markus-moser** [comment]
@lukmzig Thanks a lot, yes it works 👍
