### ISSUE TITLE
[Custom Metadata] Serializer exception

### ISSUE THREAD

**Issue by markus-moser** [pimcore/studio-backend-bundle#290]
We had a similar case also in the versions API: #267

When a asset metadata attribute contains multiple cars we get an exception like this:

![image](https://github.com/user-attachments/assets/03eed4df-853b-48fd-a9e6-73504dc5f07b)

Not sure if this needs to be solved in the backend bundle or will be part of the asset metadata class definitions implementation? The multi releation data type is part of this bundle but not of the core.

**Comment by lukmzig** [comment]
I would say we should fix this in the backend bundle for now so its possible to use the endpoint and then adapt further when working on asset metadata class definitions implementation.

Should be resolved by https://github.com/pimcore/studio-backend-bundle/pull/293
