### ISSUE TITLE
[Asset Patch Update] Metadata is not updated after a successful request

### ISSUE THREAD

**Issue by vin0401** [pimcore/studio-backend-bundle#307]
**Description**

Sending an patch request will result in a 200 Response, but after requesting the asset again, the asset data is not changed.

**Reproduction**

Example Payload:

```
{"data":[{"id":296,"metadata":[{"name":"author","data":"Peter Griffin"}]}]}
```

**Comment by mattamon** [comment]
@vin0401 Could not reproduce the issue. I do see one other problem. If the metadata does not exist in the first place, nothing can be updated. So if the author is not already in the existing fields, nothing will be updated.
I will investigate this and make it possible to also update predefined metadata via the patch method

**Comment by mattamon** [comment]
@vin0401 you can now also add entries in the patch, if they are predefined metadata.

A follow up is needed though for languages see #323

**Comment by vin0401** [comment]
Thanks a lot. :) Now it works for me. :)
