### ISSUE TITLE
Data Object Tree - order by key vs. order by index

### ISSUE THREAD

**Issue by markus-moser** [pimcore/studio-backend-bundle#320]
This is a follow up issue to https://github.com/pimcore/studio-ui-bundle/issues/261.

This functionality needs to be implemented:

![image](https://github.com/user-attachments/assets/afd6029d-017e-4279-b4d9-56655c882e79)

We first need to implement it in the GDI - see https://github.com/pimcore/generic-data-index-bundle/issues/197

**Comment by lukmzig** [comment]
Duplicate of https://github.com/pimcore/studio-backend-bundle/issues/402
Resolved by https://github.com/pimcore/studio-backend-bundle/pull/405
