### ISSUE TITLE
[Assets] Difference fixedCustomSettings and dynamicCustomSettings?

### ISSUE THREAD

**Issue by markus-moser** [pimcore/studio-backend-bundle#377]
* What's the difference between `fixedCustomSettings` and `dynamicCustomSettings`?
* Why do I get the `embeddedMetadata` and `embeddedMetaDataExtracted` in both nodes with different values?

![image](https://github.com/user-attachments/assets/a0b83395-dd47-44ab-a144-3c5d158935c9)

**Comment by lukmzig** [comment]
Fixed custom settings should contain only embeddedMetadata and embeddedMetaDataExtracted as these are consistent across the assets. Rest is dynamic. There was a small issue introduced by renaming the metadata but should be now resolved with 
https://github.com/pimcore/studio-backend-bundle/pull/379

**Comment by markus-moser** [comment]
Thanks, now it's fine and works
