### ISSUE TITLE
[Notes & Events] Note type endpoint

### ISSUE THREAD

**Issue by markus-moser** [pimcore/studio-backend-bundle#384]
The list of note types is configurable in the old UI therefore we would need a endpoint for the list of note types in the new UI too. 

![image](https://github.com/user-attachments/assets/2f1247ab-f5d1-4e43-b932-92fd9c267952)

**Comment by lukmzig** [comment]
Hi @markus-moser, the new endpoint was added here: https://github.com/pimcore/studio-backend-bundle/blob/1.x/src/Note/Controller/Element/TypeController.php#L50

**Comment by markus-moser** [comment]
Thanks a lot!

**Comment by mattamon** [comment]
Solved with #387
