### ISSUE TITLE
Problem when requesting 2 version preview image streams from the same asset ID in parallel

### ISSUE THREAD

**Issue by markus-moser** [pimcore/studio-backend-bundle#393]
When two version preview images with different binary content but the same asset image ID are requested in parallel or within a very short amount of time both return the same binary content:

![image](https://github.com/user-attachments/assets/362cca8a-7951-4659-824b-1b907515757e)

This results in the problem that sometimes in the version comparison both images look the same allthough the binary content is different.

I was able to "fix" it by adding this line:
![image](https://github.com/user-attachments/assets/561995d1-7154-4e40-9fb6-a949b07edea7)

So it seems that there are some kind of race condition in the filesystem as the same filenames are used.

**Comment by jdreesen** [comment]
Note that Symfony recently removed `uniqid()` completely from its codebase: https://github.com/symfony/symfony/issues/57588
