### ISSUE TITLE
[Schedules| Allow creating new schedules in one go

### ISSUE THREAD

**Issue by markus-moser** [pimcore/studio-backend-bundle#408]
The schedules list needs to be saved always alltogether either when saving the element or when pressing "Save scheduled tasks". Therefore it is hard to manage to create individual requests for each single row. 

The `/studio/api/schedules/{elementType}/{id}` `PUT` call allows updating of a whole list of schedule entries. It also manages deletions perfectly. So the only case which currently does not work is adding new schedules. 

Would it be possible to add this functionality and allow also the creation of new schedule entries (e.g. by leaving out the ID or as null value)?

**Comment by mattamon** [comment]
@markus-moser added it with #416.

**Comment by markus-moser** [comment]
@mattamon Great, thanks a lot!
