### ISSUE TITLE
Dependencies endpoints for data objects do not work correctly

### ISSUE THREAD

**Issue by markus-moser** [pimcore/studio-backend-bundle#437]
The following endpoint currently does not work:

`/studio/api/dependencies/data-object/82?page=1&pageSize=20&dependencyMode=required_by``

![image](https://github.com/user-attachments/assets/a2f6ad6c-8462-4e74-b01a-eb5e5a9d563e)

I guess this happens because of our various different spellings for the data object type (`object`, `data-object`, `dataObject`)

Maybe it helps using the `ElementType::fromShortValue()` method instead of the `ElementType::tryFrom()`?

**Comment by lukmzig** [comment]
@markus-moser thank you for the suggestion, now it seems to be working as expected!

**Comment by markus-moser** [comment]
@lukmzig thanks a lot
