### ISSUE TITLE
[Listing-actions] Batch-Edit/CSV-Export/ZIP-Download

### ISSUE THREAD

**Issue by vin0401** [pimcore/studio-backend-bundle#440]
For now it is only possible to interact with the endpoints for Batch-Edit/CSV-Export/ZIP-Download via a list of IDs.

But it would nice to have the possibility to address either these endpoints or new defined ones by parent id.
For example we can trigger a ZIP-Download via Asset Tree.

And there is another case for the listing. When no row is selected, the total of the current grid config should be exported.
So I guess we also have to add the grid filters to these endpoints. 

- [x] #472 
- [x] #473 
- [x] #494

**Comment by vin0401** [comment]
One thing I forgot to mention, that was brought up by @markus-moser.

We also should have some kind of configurable limitation for the ZIP-Download file size.
Because a huge export of Assets could easily clutter the disk of the server.
For sure it would also be good to have a corresponding error-code/-message. So that we can notice the user, about the reasons why they are not allowed to upload there ZIPs in that specific case.

**Comment by mattamon** [comment]
> One thing I forgot to mention, that was brought up by @markus-moser.
> 
> We also should have some kind of configurable limitation for the ZIP-Download file size. Because a huge export of Assets could easily clutter the disk of the server. For sure it would also be good to have a corresponding error-code/-message. So that we can notice the user, about the reasons why they are not allowed to upload there ZIPs in that specific case.

@vin0401 this is already the case. https://github.com/pimcore/studio-backend-bundle/blob/1.x/src/Asset/Service/ExecutionEngine/ZipService.php#L287

We will switch the exception type though https://github.com/pimcore/studio-backend-bundle/pull/455 since this makes it more clear and this can be translated in the frontend better if the http status code is 413 instead of a generic 500 error

**Comment by mattamon** [comment]
Closed by #472 #473 and #494
