### ISSUE TITLE
[Notes & Events] Data objects API problem

### ISSUE THREAD

**Issue by markus-moser** [pimcore/studio-backend-bundle#443]
The notes and events API has a problem related to the spelling of our `data-object` type.

With this URL I do not receive entries:
`/studio/api/notes/data-object/82?page=1&pageSize=20`

Whereas with this one it works:
`/studio/api/notes/object/82?page=1&pageSize=20`

Could you please change it so that `data-object` as element type works?

I think we have the same problem also for the endpoint for adding notes. When I try to add a new `data-object` note I end up with an entry without ctype in the database:

![image](https://github.com/user-attachments/assets/de24868c-fbd2-47c8-996e-9bfaa6a216ab)

**Comment by lukmzig** [comment]
Hi @markus-moser, thank you for reporting the issue, should be now working as expected.

**Comment by markus-moser** [comment]
Thanks it works now
