### ISSUE TITLE
[Tags] Data objects API problem

### ISSUE THREAD

**Issue by markus-moser** [pimcore/studio-backend-bundle#444]
We have a similar problem like #443 also for tags.

This call does not work:

`/studio/api/tags/data-object/82`

whereas this one is ok:
`/studio/api/tags/object/82`

Please check also the other tag related endpoints so that we have `data-object` as element type everywhere, thanks.

**Comment by lukmzig** [comment]
Hi @markus-moser, thank you for reporting the issue, should be now working as expected.
