### ISSUE TITLE
[Asset] CSV Export. Add permission check from index

### ISSUE THREAD

**Issue by martineiber** [pimcore/studio-backend-bundle#453]
and do not use the database. 

See.. https://github.com/pimcore/studio-backend-bundle/commit/255323afba2ebbe4cfd18dd0bcdecc4b6324caa9#diff-46b2c38d70791c2391cd6c72f8e3b268ed1d58a87dcfa9d2a8b570960de41247R75

**Comment by mattamon** [comment]
Resolved by #459
