### ISSUE TITLE
Add default image asset metadata (title, alt, copyright) to endpoints

### ISSUE THREAD

**Issue by markus-moser** [pimcore/studio-backend-bundle#464]
In the classic bundle the default metadata attributes (title, alt, copyright) are added to the UI in ExtJS when the list is empty:

https://github.com/pimcore/admin-ui-classic-bundle/blob/c68397e4e4fa83d6179e1a04b75fc28f2747a4ac/public/js/pimcore/asset/metadata/grid.js#L30

Can we add them to the API instead so that we do not need to handle this in the UI?

**Comment by mattamon** [comment]
Could you please describe the use case a little more. The description does not give me a lot to go on. 

Does this only concern the grid? What do you mean by the list is empty?
Does this have something to do with the grid config?

**Comment by markus-moser** [comment]
It has nothing to do with the grid config.

It's all about the asset metadata edit list of a single asset image.
ExtJS adds a state like this when there are no entries:

![image](https://github.com/user-attachments/assets/d25b584d-543a-4a8e-b0e6-e63456006c2c)

**Comment by mattamon** [comment]
This is only if you install the enterprise bundle https://github.com/pimcore/asset-metadata-class-definitions

You can see the difference on https://demo.pimcore.fun/admin/ and https://demo.pimcore.com/admin/

What you suggest is to add always add the title, alt and copyright on this route http://localhost/studio/api/docs#/Assets/asset_custom_metadata_get_by_id?

**Comment by markus-moser** [comment]
No this happens independently of the class definitions bundle. Please take a look at this code:

https://github.com/pimcore/admin-ui-classic-bundle/blob/c68397e4e4fa83d6179e1a04b75fc28f2747a4ac/public/js/pimcore/asset/metadata/grid.js#L30

Yes, my suggestions is to always add it when there are no metadata fields defined to this route. I know that sounds a bit strange but this is how it actually works in the classic bundle onExtJS side.
