### ISSUE TITLE
[DataObject]: Apply dynamic data to data object layout endpoint

### ISSUE THREAD

**Issue by markus-moser** [pimcore/studio-backend-bundle#528]
The layout endpoint (e.g. `/pimcore-studio/api/data-objects/1180/layout`) currently does not apply dynamic data like for example the select options if a select option provider is configured.

In the classic bundle the result looks like this:
![Image](https://github.com/user-attachments/assets/97bb7bfd-654d-4d9c-9a53-74bd4fbd6dd1)

Whereas in Studio like this:
![Image](https://github.com/user-attachments/assets/ad8e28fd-baf8-4fa6-99fb-a21187668e08)

Same applies also to e.g. the language select data type.

I guess it's all about respecting the `enrichLayoutDefinition` methods:
https://github.com/pimcore/pimcore/blob/322366f2d0d7613a0ce7ac796092f733b165008f/models/DataObject/ClassDefinition/Data/Select.php#L270

See:
https://github.com/pimcore/pimcore/blob/322366f2d0d7613a0ce7ac796092f733b165008f/models/DataObject/Service.php#L1347

**Comment by lukmzig** [comment]
@markus-moser thank you for the hint, this seems to resolve the mentioned issue and return the data s in the classic UI.

**Comment by markus-moser** [comment]
@lukmzig Thanks it works fine. Unfortnately I found at least one special case:

#534
