### ISSUE TITLE
[DataObject]: Apply dynamic data for user type to layout endpoint

### ISSUE THREAD

**Issue by markus-moser** [pimcore/studio-backend-bundle#534]
This is a follow-up issue to #528. Currently it does not work for the user datatype. There we have the situation that it's not built by using the `enrichLayout` methods. I guess because this mechanism with the layout enrichment was invented later then the user datatype.

https://github.com/pimcore/pimcore/blob/11.x/models/DataObject/ClassDefinition/Data/User.php#L42

The easist solution would be to set the admin mode for the studio backend endpoints:
https://github.com/pimcore/pimcore/blob/11.x/lib/Pimcore.php#L53

Otherwise we could also refactor the data type in the core to use the `enrichLayout` approach. But I guess we will also have other situations where the admin mode is relevant.

**Comment by lukmzig** [comment]
@markus-moser inmho there should be some kind of solution in studio which would allow us to use similiar approach as here:
https://github.com/pimcore/pimcore/blob/11.x/bundles/CoreBundle/src/EventListener/PimcoreContextListener.php#L81

otherwise we will have similiar issues in multiple cases. Maybe you can discuss what approach should studio have in arch round :)

**Comment by markus-moser** [comment]
@lukmzig I totally agree. Please let's solve it with a similar approach/general context specific listener. We will need this anyways. Even in the generated class definitions (e.g. `Pimcore\Model\DataObject\Car`) we have an if based on this admin mode. Therefore it would be really complex to do something different in studio. Let's keep the approach like in the classic bundle! Also the other topics like "hide unpublishd" or "localizedfields get fallback values" should be handled based on the context.

**Comment by lukmzig** [comment]
> [@lukmzig](https://github.com/lukmzig) I totally agree. Please let's solve it with a similar approach/general context specific listener. We will need this anyways. Even in the generated class definitions (e.g. `Pimcore\Model\DataObject\Car`) we have an if based on this admin mode. Therefore it would be really complex to do something different in studio. Let's keep the approach like in the classic bundle! Also the other topics like "hide unpublishd" or "localizedfields get fallback values" should be handled based on the context.

I assume for that we will need some kind of context attached from every request which is coming from the Studio UI, is that possible?

**Comment by markus-moser** [comment]
> I assume for that we will need some kind of context attached from every request which is coming from the Studio UI, is that possible?

As the backend API is only relevant for studio and related bundles each request is coming from studio. So we should do it based on e.g. the route...

**Comment by lukmzig** [comment]
> > I assume for that we will need some kind of context attached from every request which is coming from the Studio UI, is that possible?
> 
> As the backend API is only relevant for studio and related bundles each request is coming from studio. So we should do it based on e.g. the route...

But in this case we can do it on every request in the studio Back-end no? We do not need to do it for every route separately

**Comment by markus-moser** [comment]
> But in this case we can do it on every request in the studio Back-end no? We do not need to do it for every route separately

Exactly. Once for all requests in studio backend. Not route specific - with route I only meant the route prefix for studio (`/pimcore-studio/api/`). This could potentially be a way to identify studio requests within a request listener. But for sure there are plenty of other ways to solve it. At the end we should just enable the admin mode for all requests.

**Comment by lukmzig** [comment]
> > But in this case we can do it on every request in the studio Back-end no? We do not need to do it for every route separately
> 
> Exactly. Once for all requests in studio backend. Not route specific - with route I only meant the route prefix for studio (`/pimcore-studio/api/`). This could potentially be a way to identify studio requests within a request listener. But for sure there are plenty of other ways to solve it. At the end we should just enable the admin mode for all requests.

Ah, now I got it, thank you!

**Comment by lukmzig** [comment]
@markus-moser should be resolved now

**Comment by markus-moser** [comment]
@lukmzig Thx, it works as it should now!
