### ISSUE TITLE
Object Workflow

### ISSUE THREAD

**Issue by xIrusux** [pimcore/studio-backend-bundle#555]
![Image](https://github.com/user-attachments/assets/d8427689-b751-4f36-acb7-3b2f6b113485)
I am getting an error response when trying to submit a workflow action for objects. 

here my api call with parameters:
![Image](https://github.com/user-attachments/assets/51605608-5255-4c85-9961-968a82d64ee3)

The class name of the object is "Car":
![Image](https://github.com/user-attachments/assets/8eb6f48d-09eb-4f82-8459-5e73248e0ac1)

Which is the same class name that the workflow is specified for:
![Image](https://github.com/user-attachments/assets/8d861ac0-21a9-45f1-91f8-7d406d326dc4)

When I remove the condition of the workflow I am getting the below error:
![Image](https://github.com/user-attachments/assets/aefa4c34-8d05-4121-b963-6ec4be1e8561)
Which may suggest there is a problem with getting Workflows for objects?

![Image](https://github.com/user-attachments/assets/c8175ef4-f9c4-4498-a03d-823642c418ab)
For consistency purposes we may want to use 'data-object' instead of 'object' here.

**Comment by lukmzig** [comment]
@xIrusux 
based on your screenshot you are passing incorrect values to the endpoint:
- you should provide the workflow name/ID which is `product_data_enrichment` but you are passing `product_data_enrichment_workflow` which does not exists (as error message says, it cannot find workflow with an ID which you provided)
- same for the transition, there an ID should be passed


I adapted the schema in this PR #623 so its more clear, the parameters are renamed now

Regarding the exception, this can be also interpreted as a validation error - there cannot be expression selected with no condition provided. I added a catch block in studio so we filter out this invalid workflow definitions
