### ISSUE TITLE
Adjust CustomMetadata

### ISSUE THREAD

**Issue by Corepex** [pimcore/studio-backend-bundle#564]
Hi Guys, 

I noticed a few things according to the custom metadata.

**1. Empty CustomMetadata**

If you add a custom metadata entry to an asset in the UI we send it to the backend as json which looks like the following:

```json
...
{
    "additionalAttributes": [],
    "name": "foobar",
    "type": "input",
    "language": "",
    "data": null
}
...
```

This entry won't be saved since `data` is `null`. 
To save an empty entry, we must set `data` to `""`. 
IMHO, saving the entry if `data` is `null` would be good since empty entries also get returned with `data: null`.

**2. Disappearing Entries**

Each asset has the `title`, `alt` and `copyright` custom metadata entries per default. 
If you now add a new entry and save it, the default entries will disappear.

We should change that ...

**Comment by mattamon** [comment]
Why do you send `additionalAttributes`?
This is only for the output model. This is not even listed in the schema.

Saving with data null seems to be a problem in the core. Seems like that it then is not saved. Also if you check the original request when adding metadata in the classic ui it is also sent with an empty string. Of course we can change this too. Question is, why would you save it with null in the first place? 


2. See this issue and discussion with @markus-moser 
https://github.com/pimcore/studio-backend-bundle/issues/464 especially comment https://github.com/pimcore/studio-backend-bundle/issues/464#issuecomment-2399783396
They are only added if there are no metadata fields are defined.

Are you sure you want to change this behaviour?

**Comment by Corepex** [comment]
@mattamon thanks for the detail information :)

Although `null` would be better, in my opinion, we will stick to `""` for now. 
We will adjust that in the future ...
