### ISSUE TITLE
[Data Object Tree] Add className property

### ISSUE THREAD

**Issue by markus-moser** [pimcore/studio-backend-bundle#568]
For the D&D to relation attributes we need the className system field from the GDI in the tree endpoint.

**Comment by markus-moser** [comment]
Related to #566

**Comment by markus-moser** [comment]
An important aspect here is that we need to respect the user permissions!

**Comment by lukmzig** [comment]
@markus-moser not sure what do you need here ...the class name property is existing in the tree endpoint already. Please elaborate what should be changed, what do you need regarding the permissions

**Comment by markus-moser** [comment]
@lukmzig Sorry, you are right, it's already there at the endpoints. So no todos left - need to check it on frontend side where it gets lost ;) Thanks for checking!
