### ISSUE TITLE
[Bug]: Issue where default metadata PATCH calls are unsuccessful

### ISSUE THREAD

**Issue by xIrusux** [pimcore/studio-backend-bundle#574]
### Studio API version

0.0.1

### Steps to reproduce

 ![Image](https://github.com/user-attachments/assets/a5b86fe3-f9cb-4428-88e7-136f20735fcc)

as discussed with Matthias. 
There is already a fix. 
This issue is for documentation purposes

### Actual Behavior

default metadata can not be updated via PATCH

### Expected Behavior

default metadata can be updated via PATCH

**Comment by mattamon** [comment]
Resolved by #573

**Comment by xIrusux** [comment]
update: After some testing there is still a tweak to be made here. 
The update works when the patch is a change of the existing default metadata field not when the default metadata was previously empty.

**Comment by xIrusux** [comment]
update - tested and considered fixed
