### ISSUE TITLE
[Data Object Editor] Structure for field collections

### ISSUE THREAD

**Issue by vin0401** [pimcore/studio-backend-bundle#588]
The current structure for the field collections is a bit limiting when it comes to new information we want to add to the field collections:

![Image](https://github.com/user-attachments/assets/f662ee1a-7f25-4005-8fa3-5cd63f7403e4)

Instead we should nest the data in a own property to avoid naming conflicts:

```
FieldCollectionExample: [
    0: {
        type: 'MyCollction',
        data: {
            field1: 'value',
            field2: 'value'
        }
    }
]
```

**Comment by lukmzig** [comment]
Part of https://github.com/pimcore/studio-backend-bundle/issues/566
