### ISSUE TITLE
[Data Object Editor] Field-Collections with block and localized fields not working

### ISSUE THREAD

**Issue by vin0401** [pimcore/studio-backend-bundle#597]
The following field collection is causing errors on the data object endpoint:

![Image](https://github.com/user-attachments/assets/644cde29-6a49-4e23-accf-6cd774f1a5b4)

[fieldcollection_localizedBlock_export.json](https://github.com/user-attachments/files/17950692/fieldcollection_localizedBlock_export.json)

When I add some data in the classic UI it will cause the following error in Studio:

![Image](https://github.com/user-attachments/assets/a62dbf0c-548d-44e3-9440-c0bf7ad04ca2)

The same request without any prefilled data will end up in this error:

![Image](https://github.com/user-attachments/assets/03f9277a-6722-4687-b068-fb9f7f2c5955)

**Comment by martineiber** [comment]
@vin0401 Should be fixed with https://github.com/pimcore/studio-backend-bundle/pull/609
