### ISSUE TITLE
[Docs] ACLs in installation docs wrong

### ISSUE THREAD

**Issue by fashxp** [pimcore/studio-backend-bundle#600]
### Studio API version

*

### Steps to reproduce

when adding 
```
    access_control:
      - { path: ^/pimcore-studio/api/(docs|docs.json|translations)$, roles: PUBLIC_ACCESS }
      - { path: ^/pimcore-studio, roles: ROLE_PIMCORE_USER }
```

To the security.yaml, then when opening pimcore-studio user gets redirected to some login page - in case of demo to the frontend login. 
Either we need to remove the `- { path: ^/pimcore-studio, roles: ROLE_PIMCORE_USER }`, we need to fix the path in that line, or we need to fix the firewall settings so they listen to `/pimcore-studio` as well...

### Actual Behavior

.

### Expected Behavior

.

**Comment by fashxp** [comment]
needs to be fixed here as well 

https://github.com/pimcore/studio-backend-bundle/blob/1.x/doc/00_Installation.md?plain=1#L30-L31

**Comment by martineiber** [comment]
Good Point. Did not see that. 

Will change it.
