### ISSUE TITLE
[Bug] csv download in list view does not work

### ISSUE THREAD

**Issue by heigpa** [pimcore/studio-backend-bundle#602]
**Steps to reproduce**

- Login as admin
- Open a folder with assets
- Switch to the list view
- Mark some assets
- Start csv export

**Actual behaviour**
![Image](https://github.com/user-attachments/assets/ee1cb4ea-406d-48db-8a2e-4d5e2cc04ddc)

- Download does not work

**Expected behaviour**
- csv file should be downloaded

**Environment**

- Nightly build

**Comment by fashxp** [comment]
seems this is related with the preview column ... when this is removed, it works

**Comment by markus-moser** [comment]
Yes, I'll move it to the backend - this is a problem in the backend

**Comment by mattamon** [comment]
@markus-moser we do fire a specific `job-failed` event in mercure for this kind of cases.

![Image](https://github.com/user-attachments/assets/6de3c4d2-eedb-41c3-b8c1-1db42a2fa4a1)

In the SSE it specificly states that the preview column is not exportable. 
Of course we could change this an just skip over non exportable columns, but otherwise the user never gets an info why this column was not exported.

**Comment by markus-moser** [comment]
@mattamon I see - to be honest I would really prefer to just skip them. The preview for example is a default column which will be visible in most cases and then almost each export ends in an error...

**Comment by markus-moser** [comment]
But for sure the triggered errors need to be respected by the frontend view too

**Comment by mattamon** [comment]
> But for sure the triggered errors need to be respected by the frontend view too

Maybe we should also add this info to the column config, so FE knows which columns can be exported and do not send it to the BE in the first place?

**Comment by markus-moser** [comment]
> Maybe we should also add this info to the column config, so FE knows which columns can be exported and do not send it to the BE in the first place?

Yes I thought about this too, I would say this is the best solution, let's solve it like this 👍

**Comment by mattamon** [comment]
@markus-moser I added the flag + I skip over columns that are not exportable now instead of throwing an exception

**Comment by markus-moser** [comment]
Nice, thanks a lot 👍
