### ISSUE TITLE
Wrong behaviour in `asset_replace` endpoint

### ISSUE THREAD

**Issue by Corepex** [pimcore/studio-backend-bundle#605]
Hi guys, 

I implemented the "upload new version" function in the frontend and used the following endpoint for that: 
http://localhost/pimcore-studio/api/docs#/Assets/asset_replace

I noticed that this endpoint changes the name of the whole asset. It should only patch the extension (if it is a different one)
soo `foobar.png` becomes `foobar.jpg`. 

Would be great if you could change that ...
If there are any questions let me know :)

**Comment by lukmzig** [comment]
@Corepex I am unfortunately unable to reproduce this .... for me the behavior is exactly same as you describe that it should be.
It only changes jpg to png for example, name stays the same. If you already have another asset existing with the same name before, then the system adds automatic suffix, which is correct.

**Comment by Corepex** [comment]
@lukmzig thanks for checking. I will check it again afterwards and come back to that :)

**Comment by Corepex** [comment]
@lukmzig I looked deeper into that problem, and it seems I found an edge case. 

If I have an existing image called `foobar.jpg` and I override it with a file that has **another name but the same extension** (in that case `.jpg`) it will also replace the name ...

So for example
`foobar.jpg` -> uploading `buzz.png` becomes `foobar.png` (just the extension changes - as it should be)
`foobar.jpg` -> uploading `buzz.jpg` becomes `buzz.jpg` (the name changes ...)

I hope it's understandable ...

**Comment by lukmzig** [comment]
@Corepex thank you for having a deeper look, I was now able to reproduce the issue and found a fix. Should be working as expected now :)
