### ISSUE TITLE
[Dependency] Permissions

### ISSUE THREAD

**Issue by mattamon** [pimcore/studio-backend-bundle#66]
Currently there is a permissions check for the requested element only. 
But the according dependencies have to be checked for the `listing` permission too, see existing implementation: https://github.com/pimcore/pimcore/blob/e9c9e2d43e56502f000a38c59eb7f92c6029c347/models/Element/Service.php#L192

The idea is to have an endpoint in `generic-data-index-bundle` that can check permissions for more than one object, thus providing a fast way to check permissions on a set of elements.

**Comment by markus-moser** [comment]
@mattamon @alexz707 

I implemented now a approach in the generic data index bundle to search for all elements (assets, documents, data objects) in parallel and search modifiers to filter by dependencies (see this PR https://github.com/pimcore/generic-data-index-bundle/pull/159).

The dependencies are now indexed into the search index. This is the only approach which could work without major performance drawbacks. 

The usage is simple. Please use the new `ElementSearchService` like described here:

https://github.com/pimcore/generic-data-index-bundle/tree/1.x/doc/04_Searching_For_Data_In_Index#element-search-service

together with the new dependency related search modifiers:

https://github.com/pimcore/generic-data-index-bundle/tree/1.x/src/Model/Search/Modifier/Filter/Dependency

The usage of the `ElementSearchService` works exactly the same like for the other search services (so it's possible to pass the user etc.)

The data in the generic data index needs to be reindexed to make it work. Therefore please restart your message workers/supervisor and call the following command before `bin/console generic-data-index:update:index`
